global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "photonic_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'photonic-attention'
    static_configs:
      - targets: ['photonic-attention:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-exporter:9445']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']