apiVersion: v1
kind: Service
metadata:
  labels:
    app: photonic-flash-attention
    region: asia-pacific
  name: photonic-flash-attention-service-asia-pacific
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: photonic-flash-attention
    region: asia-pacific
  type: LoadBalancer
