apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: photonic-flash-attention-hpa-us-east
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: photonic-flash-attention-us-east
