apiVersion: v1
kind: Service
metadata:
  labels:
    app: photonic-flash-attention
    region: us-east
  name: photonic-flash-attention-service-us-east
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: photonic-flash-attention
    region: us-east
  type: LoadBalancer
